
name: 'Pixee'

on:
  
  pull_request:
    branches:
      - main
    types: [opened, reopened, update,synchronize]

permissions:
  contents: write

jobs:
  pixee_fix:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      id-token: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run Python script to create PR
        uses: docker://codemodder/ci-integrations:latest@sha256:221f6c8d6a96c60ae3ff2cac5d94301818d585014506ea59de7c831e65c2a566
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
