name: Analyze with Semgrep and Fix with Pixee

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Semgrep
        run: |
          python3 -m pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep --config auto --sarif --output semgrep-results.sarif.json 

      - name: Fix with Pixee
        uses: pixee/upload-tool-results-action@9394b64cae9cd00d86095b2b8dc6423d45507434 # v2.5.0
        with:
          tool: semgrep
          file: semgrep-results.sarif.json
